### ISSUE TITLE
High CPU with 2023.12

### ISSUE THREAD

**Issue by basilfx** [andreas-berg/hass-entsoe-dayahead#2]
I've added this integration, but since I installed it, I have high CPU usage.

Using py-spy, this is the top:

<img width="690" alt="image" src="https://github.com/andreas-berg/hass-entsoe-dayahead/assets/815976/5f3a02ea-c243-429b-935d-81deba4b90fd">

For some reason, it keeps invoking these three functions over and over. The integration works fine though.

Disabling the integration solves the issue, but requires a restart of HASS (it is probably not unloading properly).

Using Home Assistant 2023.12.2.

**Comment by andreas-berg** [comment]
Thanks for the issue report and py-spy-logs, sorry for the slow response.
This should be fixed now in the main-branch. 
Let's keep this issue open a few days until I've verified that the Sensor updates correctly. 
I also removed some "RestoreSensor"-code since I wasn't hass-savvy enough to figure out how HomeAssistant stores/restores these values from db.

**Comment by basilfx** [comment]
Thank you, and no worries.

So far it looks good, and I don't see high CPU usage anymore.

**Comment by andreas-berg** [comment]
Seems to run quite fine now, so closing the issue
